name: CICD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: echo "Checking out the code"

  build:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: Build Docker Container
        run: echo "Docker container build successful"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test the Container
        run: echo "Testing completed successfully"

  deploy:
    if: ${{ github.event.inputs.environment == 'dev' }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy the Container
        run: echo "Deploying container to server..."
