name: python lint

on:
  push:
    branches: [main]

jobs:
  validate: 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # 1. Yahan versions list karein
        python-v: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: setup python
        uses: actions/setup-python@v5
        with:
          # 2. Hardcoded "3.13" ki jagah matrix variable use karein
          python-version: ${{ matrix.python-v }}

      - name: Install Linting Tool
        run: pip install flake8

      - name: Run Lint
        # Sirf app.py ko check karega
        run: flake8 app.py
